endEffectorPoseSubscriber = rossubscriber('/dobot_magician/end_effector_poses'); 
pause(2);

currentEndEffectorPoseMsg = endEffectorPoseSubscriber.LatestMessage;

currentEndEffectorPosition = [currentEndEffectorPoseMsg.Pose.Position.X,...
                              currentEndEffectorPoseMsg.Pose.Position.Y,...
                              currentEndEffectorPoseMsg.Pose.Position.Z];

currentEndEffectorQuat = [currentEndEffectorPoseMsg.Pose.Orientation.W,...
                          currentEndEffectorPoseMsg.Pose.Orientation.X,...
                          currentEndEffectorPoseMsg.Pose.Orientation.Y,...
                          currentEndEffectorPoseMsg.Pose.Orientation.Z];

[roll,pitch,yaw] = quat2eul(currentEndEffectorQuat);
